### ISSUE TITLE
Extra conversation participants

### ISSUE THREAD

**Issue by filipedematos** [BryceStevenWilley/visioning_texts#2]
Hi Bryce! Congratulations on your tool, it really looks awesome! It was shared in r/dataisbeutiful

Tried it myself but got this instead:

<img width="1440" alt="Screenshot 2020-01-20 at 16 13 20" src="https://user-images.githubusercontent.com/60107261/72741561-cfc73800-3b9f-11ea-8534-a0b5d0330e59.png">

The file is from a whatsapp backup, not english though, portuguese.

Thank you in advance!

**Comment by samsamduvent** [comment]
Hello, i come from reddit as well and have the same problem. followed the instruction and it didn't work. Whatsapp in english.
Tried it locally and on the web in chrome and safari.

**Comment by BryceStevenWilley** [comment]
So, when you say WhatsApp backup, do you mean the full WhatsApp backup file of all conversations?  I only had time to handle 2 people conversations, and it looks like you uploaded a file with a lot of different people in it.

**Comment by samsamduvent** [comment]
Just 1-1 conversion. I exported the chat, unzipped the file and uploaded it

**Comment by Vidhin05** [comment]
@BryceStevenWilley This is a typical line in my whatsapp file,
[21/12/18, 22:17:43] NAME: ‎TEXT
What does your's look like?

**Comment by Vidhin05** [comment]
This issue seems connected to [https://github.com/BryceStevenWilley/visioning_texts/issues/6](url)

**Comment by BryceStevenWilley** [comment]
That's likely the issue: my WhatsApp file looks like:
5/21/19, 15:39 - NAME: TEXT

No braces or anything. Thanks for the help @Vidhin05

**Comment by BryceStevenWilley** [comment]
I just pushed some changes that should handle `[` WhatsApp output. @Vidhin05, @filipedematos, @samsamduvent, let me know if it fixed anything for you.  If it didn't, could you look into the console log and post any errors?

**Comment by slevin1991** [comment]
Same problem as OP but now it's blank when I run my file. 

Typical line: 5/21/19, 15:39 - NAME: TEXT

Console info:
math.js:68 Uncaught TypeError: Cannot read property 'concat' of undefined
    at math.js:68
    at Array.reduce (<anonymous>)
    at split_b_k_whatsapp (math.js:62)
    at FileReader.<anonymous> (graphs.js:488)

**Comment by BryceStevenWilley** [comment]
Thanks @slevin1991, I made a dumb mistake and broke some other fixes.  Sholud be fixed by https://github.com/BryceStevenWilley/visioning_texts/commit/73734339bbcac6fb90653d064983c26c2f519a75.

**Comment by Vidhin05** [comment]
@BryceStevenWilley https://github.com/BryceStevenWilley/visioning_texts/commit/799f6e84709af7696ff22de0c3b60574a5272c95 Fixed everything for me! Thank you

**Comment by slevin1991** [comment]
EDIT: It's because my .txt file is too big. It's at 30mb, just had to wait for it to run. 

It still shows up as blank for me :(

Uncaught TypeError: Cannot read property 'concat' of undefined
    at math.js:109
    at Array.reduce (<anonymous>)
    at split_b_k_whatsapp (math.js:103)
    at FileReader.<anonymous> (graphs.js:488)

**Comment by samsamduvent** [comment]
@BryceStevenWilley just tested the newest version and got this from the console:

Btw a sample line of the chat file: [9/20/19, 09:31:09]


`math.js:109 Uncaught TypeError: Cannot read property 'concat' of undefined
    at math.js:109
    at Array.reduce (<anonymous>)
    at split_b_k_whatsapp (math.js:103)
    at FileReader.<anonymous> (graphs.js:488)`

**Comment by BryceStevenWilley** [comment]
@samsamduvent, (also everyone else still having problems in this thread), I've fixed much more of the date parsing issues, and have confirmed it with some tests. Check it out again, and let me know how it goes

**Comment by samsamduvent** [comment]
@BryceStevenWilley great it works! thanks a lot. Still having #8 though.

**Comment by BryceStevenWilley** [comment]
Awesome, thanks! I'll close this issue for now, and will try to make some progress on #8 this week.
